import{a}from"./assets/vendor-a61d8330.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const c of n.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&l(c)}).observe(document,{childList:!0,subtree:!0});function o(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerpolicy&&(n.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?n.credentials="include":t.crossorigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function l(t){if(t.ep)return;t.ep=!0;const n=o(t);fetch(t.href,n)}})();const d="live_Io4faX6h8wEC4EO7AIs6Kiq6ekje37Y3Lp4i3sJ2Kr15VnKy6tU5a2MTs7ywIkqQ";a.defaults.headers.common["x-api-key"]=d;function u(){return a.get("https://api.thecatapi.com/v1/breeds").then(e=>e.data).catch(e=>console.error("An error occurred:",e.message))}function f(e){const s=`https://api.thecatapi.com/v1/images/search?breed_ids=${e}`;return a.get(s).then(o=>o.data[0]).catch(o=>{console.error("An error occurred:",o.message)})}const r={breedSelect:document.querySelector(".breed-select"),loader:document.querySelector(".loader"),errorMessage:document.querySelector(".error"),catInfo:document.querySelector(".cat-info")};r.loader.style.display="none";r.errorMessage.style.display="none";function p(e){return`
    <div class="cat-card">
      <img class="cat-image" src="${e.url}" alt="Cat Image">
      <div class="cat-details">
        <h2 class="cat-name">${e.breeds[0].name}</h2>
        <p class="cat-description">${e.breeds[0].description}</p>
        <p class="cat-temperament"><bold>Temperament: ${e.breeds[0].temperament}</p>
      </div>
    </div>
  `}function y(e){r.catInfo.innerHTML=p(e),r.loader.style.display="none",r.catInfo.style.display="block"}function i(){r.loader.style.display="none",r.breedSelect.style.display="none",r.catInfo.style.display="none",r.errorMessage.style.display="block"}function m(e){const s=e.target.value;r.loader.style.display="block",r.catInfo.style.display="none",f(s).then(o=>{y(o),r.errorMessage.style.display="none"}).catch(o=>{i(),console.error("Error fetching cat info:",o)})}function h(){u().then(e=>{console.log("Fetched Breeds:",e),e.forEach(s=>{const o=document.createElement("option");o.value=s.id,o.textContent=s.name,r.breedSelect.appendChild(o)}),r.breedSelect.addEventListener("change",m)}).catch(e=>{console.error("Error fetching breeds:",e),i()})}h();
//# sourceMappingURL=commonHelpers.js.map
